modLoader="javafml"
loaderVersion="[36,)"
license="LGPL V3"

[[mods]]
modId="cantswimupwaterfalls"
version="1.0"
displayName="You Cannot Swim Up Waterfalls"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/you-cannot-swim-up-waterfalls"
#logoFile="logo.png"
#credits="credits"
authors="StephenBarnes"
description='''
Prevent swimming upwards in falling water.'''

[[dependencies.cantswimupwaterfalls]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cantswimupwaterfalls]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
